# Generated by Django 5.2.17 on 2026-09-22 16:35

from decimal import Decimal

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("normalized_name", models.CharField(editable=False, max_length=160, unique=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "ordering": ["name", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=24,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9_-]+$", "Use letras, números, hífen ou sublinhado."
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome da unidade")),
                ("is_active", models.BooleanField(default=True, verbose_name="Unidade ativa")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_general_admin",
                    models.BooleanField(default=False, verbose_name="Administrador geral"),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("temporary_password_expires_at", models.DateTimeField(blank=True, null=True)),
                ("session_version", models.PositiveIntegerField(default=0)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("normalized_name", models.CharField(editable=False, max_length=160, unique=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=24,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9_-]+$", "Use letras, números, hífen ou sublinhado."
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("kg", "Quilograma (kg)"),
                            ("L", "Litro (L)"),
                            ("un", "Unidade (un)"),
                        ],
                        max_length=2,
                        verbose_name="Unidade de medida",
                    ),
                ),
                (
                    "requires_expiry",
                    models.BooleanField(
                        default=True, verbose_name="Exigir validade nos recebimentos"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome da embalagem")),
                ("normalized_name", models.CharField(editable=False, max_length=140)),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                        verbose_name="Conteúdo na unidade de medida do alimento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Embalagem ativa")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentations",
                        to="core.food",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("food", "normalized_name"), name="unique_food_pack"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("base_quantity__gt", 0)), name="positive_pack"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_name", models.CharField(max_length=160)),
                ("action", models.CharField(max_length=32)),
                ("entity", models.CharField(max_length=80)),
                ("entity_id", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=240)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="core.unit"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["unit", "created_at"], name="core_audite_unit_id_e00784_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Responsável"), ("operator", "Funcionário")],
                        max_length=16,
                        verbose_name="Perfil",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Acesso ativo")),
                (
                    "unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.unit"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["unit__name"],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "unit"), name="unique_user_unit")
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Estoque mínimo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Acompanhar nesta unidade"),
                ),
                (
                    "food",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.food"),
                ),
                (
                    "unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.unit"),
                ),
            ],
            options={
                "ordering": ["food__name"],
                "constraints": [
                    models.UniqueConstraint(fields=("unit", "food"), name="unique_unit_food"),
                    models.CheckConstraint(
                        condition=models.Q(("minimum__gte", 0)), name="nonnegative_minimum"
                    ),
                ],
            },
        ),
    ]
