# Generated by Django 5.2.17 on 2026-09-24 16:59

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_protect_audit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["code", "pk"]},
        ),
        migrations.AddField(
            model_name="food",
            name="image_path",
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name="Foto"),
        ),
        migrations.AddField(
            model_name="unitfood",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Quantidade atual",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitfood",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="nonnegative_quantity"
            ),
        ),
    ]
