# Generated by Django 5.2.17 on 2026-09-24 20:00

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_food_photos_and_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="fiscal_address_match",
            field=models.CharField(
                blank=True,
                help_text="Trecho usado para reconhecer automaticamente a unidade, por exemplo Sample Street.",
                max_length=160,
                verbose_name="Referência do endereço na NF-e",
            ),
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_key",
                    models.CharField(
                        max_length=44,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{44}$", "A chave deve conter 44 números."
                            )
                        ],
                        verbose_name="Chave de acesso",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Número")),
                ("series", models.CharField(max_length=10, verbose_name="Série")),
                ("issued_at", models.DateTimeField(verbose_name="Emissão")),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="Entrega prevista"),
                ),
                (
                    "protocol",
                    models.CharField(max_length=30, verbose_name="Protocolo de autorização"),
                ),
                (
                    "authorization_received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Autorização"),
                ),
                ("supplier_cnpj", models.CharField(max_length=14, verbose_name="CNPJ do emitente")),
                ("supplier_name", models.CharField(max_length=180, verbose_name="Emitente")),
                (
                    "recipient_cnpj",
                    models.CharField(max_length=14, verbose_name="CNPJ do destinatário"),
                ),
                ("recipient_name", models.CharField(max_length=180, verbose_name="Destinatário")),
                (
                    "delivery_address",
                    models.CharField(max_length=300, verbose_name="Endereço de entrega"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total da NF-e"
                    ),
                ),
                (
                    "payments",
                    models.JSONField(default=list, editable=False, verbose_name="Pagamentos"),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        default=list, editable=False, verbose_name="Avisos de validação"
                    ),
                ),
                (
                    "signature_present",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Assinatura presente"
                    ),
                ),
                ("xml_sha256", models.CharField(editable=False, max_length=64, unique=True)),
                ("xml_content", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Aguardando conferência"),
                            ("imported", "Entrada confirmada"),
                        ],
                        default="review",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_fiscal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_fiscal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_documents",
                        to="core.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="FiscalDocumentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("line_number", models.PositiveIntegerField(verbose_name="Item")),
                (
                    "supplier_code",
                    models.CharField(max_length=60, verbose_name="Código no fornecedor"),
                ),
                ("ean", models.CharField(blank=True, max_length=20, verbose_name="EAN")),
                ("description", models.CharField(max_length=240, verbose_name="Descrição na NF-e")),
                ("ncm", models.CharField(blank=True, max_length=10, verbose_name="NCM")),
                ("cfop", models.CharField(blank=True, max_length=6, verbose_name="CFOP")),
                (
                    "commercial_unit",
                    models.CharField(max_length=12, verbose_name="Unidade na NF-e"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Quantidade na NF-e"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=10, max_digits=16, verbose_name="Preço unitário"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total do item"
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                        verbose_name="Quantidade para o estoque",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.fiscaldocument",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_document_items",
                        to="core.food",
                        verbose_name="Alimento",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "line_number"), name="unique_fiscal_document_line"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="positive_fiscal_item_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_total__gte", 0)),
                        name="nonnegative_fiscal_item_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stock_quantity__isnull", True),
                            ("stock_quantity__gt", 0),
                            _connector="OR",
                        ),
                        name="positive_fiscal_stock_quantity",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("supplier_cnpj", models.CharField(max_length=14, verbose_name="CNPJ do emitente")),
                (
                    "supplier_code",
                    models.CharField(max_length=60, verbose_name="Código no fornecedor"),
                ),
                ("ean", models.CharField(blank=True, max_length=20, verbose_name="EAN")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_mappings",
                        to="core.food",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier_cnpj", "supplier_code"), name="unique_supplier_product"
                    )
                ],
            },
        ),
    ]
