# Generated by Django 5.2.17 on 2026-09-28 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_unit_fiscal_address_match_fiscaldocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldocumentitem",
            name="expires_on",
            field=models.DateField(blank=True, null=True, verbose_name="Validade"),
        ),
        migrations.AddField(
            model_name="fiscaldocumentitem",
            name="lot_code",
            field=models.CharField(blank=True, max_length=80, verbose_name="Lote"),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("approved", "Aprovado"),
                    ("pending", "Aguardando aprovação"),
                    ("rejected", "Recusado"),
                ],
                default="approved",
                max_length=12,
                verbose_name="Situação do cadastro",
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Entrada"),
                            ("consumption", "Consumo"),
                            ("loss", "Perda"),
                            ("supplier_return", "Devolução ao fornecedor"),
                            ("stock_return", "Retorno ao estoque"),
                            ("adjustment_in", "Ajuste de entrada"),
                            ("adjustment_out", "Ajuste de saída"),
                            ("opening", "Saldo inicial"),
                            ("reversal", "Estorno"),
                        ],
                        max_length=24,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data e hora"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Motivo ou observação"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movement",
                        to="core.fiscaldocument",
                    ),
                ),
                (
                    "reversed_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="core.stockmovement",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StockMovementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Alteração do saldo"
                    ),
                ),
                ("lot_code", models.CharField(blank=True, max_length=80, verbose_name="Lote")),
                ("expires_on", models.DateField(blank=True, null=True, verbose_name="Validade")),
                (
                    "fiscal_document_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movement_item",
                        to="core.fiscaldocumentitem",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.stockmovement",
                    ),
                ),
                (
                    "unit_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_items",
                        to="core.unitfood",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["unit", "occurred_at"], name="core_stockm_unit_id_50bb44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovementitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta", 0), _negated=True), name="nonzero_stock_delta"
            ),
        ),
    ]
