# Generated by Django 5.2.17 on 2026-09-28 15:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_backfill_and_protect_stock_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalPdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_key",
                    models.CharField(
                        db_index=True,
                        max_length=44,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{44}$", "A chave deve conter 44 números."
                            )
                        ],
                        verbose_name="Chave de acesso",
                    ),
                ),
                ("original_name", models.CharField(max_length=180, verbose_name="Nome do arquivo")),
                ("page_count", models.PositiveSmallIntegerField(verbose_name="Páginas")),
                ("pdf_sha256", models.CharField(editable=False, max_length=64, unique=True)),
                ("pdf_content", models.BinaryField()),
                (
                    "validation_warnings",
                    models.JSONField(
                        default=list, editable=False, verbose_name="Avisos de validação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_xml", "Aguardando XML"),
                            ("linked", "Vinculado à NF-e"),
                        ],
                        default="awaiting_xml",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_fiscal_pdfs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdfs",
                        to="core.fiscaldocument",
                        verbose_name="NF-e",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("document__isnull", True), ("status", "awaiting_xml")),
                            models.Q(("document__isnull", False), ("status", "linked")),
                            _connector="OR",
                        ),
                        name="fiscal_pdf_status_matches_document",
                    )
                ],
            },
        ),
    ]
