# Generated by Django 5.2.17 on 2026-09-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_fiscalpdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldocument",
            name="draft_saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="draft_saved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_document_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="review_draft",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Rascunho da conferência"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="fiscal_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="core.fiscaldocument",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovementitem",
            name="fiscal_document_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement_items",
                to="core.fiscaldocumentitem",
            ),
        ),
    ]
