# Generated by Django 5.2.17 on 2026-09-28 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_fiscaldocument_draft_saved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PnaeCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True, verbose_name="Ano")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("reference", models.CharField(max_length=300, verbose_name="Referência")),
                (
                    "source_name",
                    models.CharField(max_length=180, verbose_name="Documento de origem"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="Fonte para consulta")),
                ("is_active", models.BooleanField(default=True, verbose_name="Catálogo vigente")),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="single_active_pnae_catalog",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FiscalPnaeException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="Justificativa")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando aprovação"),
                            ("approved", "Aprovada"),
                            ("rejected", "Recusada"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.food"),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pnae_exception",
                        to="core.fiscaldocumentitem",
                        verbose_name="Item da NF-e",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_pnae_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_pnae_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pnaecatalog"
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PnaeCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Código do item")),
                ("name", models.CharField(max_length=180, verbose_name="Nome no catálogo")),
                ("specification", models.TextField(blank=True, verbose_name="Especificação")),
                (
                    "acquisition_unit",
                    models.CharField(
                        choices=[("kg", "Quilograma (kg)"), ("un", "Unidade (un)")],
                        max_length=2,
                        verbose_name="Unidade de aquisição",
                    ),
                ),
                (
                    "packaging",
                    models.TextField(blank=True, verbose_name="Embalagem ou apresentação"),
                ),
                ("source_page", models.PositiveSmallIntegerField(verbose_name="Página de origem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Item permitido")),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.pnaecatalog",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pnae_catalog_items",
                        to="core.food",
                        verbose_name="Alimento no estoque",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog", "code"), name="unique_pnae_catalog_code"
                    )
                ],
            },
        ),
    ]
