# Generated by Django 5.2.17 on 2026-09-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_pnaecatalog_fiscalpnaeexception_pnaecatalogitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_name", models.CharField(max_length=180, verbose_name="Nome do arquivo")),
                (
                    "title",
                    models.CharField(
                        default="Cardápio semanal", max_length=180, verbose_name="Título"
                    ),
                ),
                (
                    "week_start",
                    models.DateField(blank=True, null=True, verbose_name="Início da semana"),
                ),
                ("week_end", models.DateField(blank=True, null=True, verbose_name="Fim da semana")),
                (
                    "nutritionist_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Nutricionista"),
                ),
                (
                    "nutritionist_registration",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Registro profissional"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("page_count", models.PositiveSmallIntegerField(verbose_name="Páginas")),
                ("pdf_sha256", models.CharField(editable=False, max_length=64, unique=True)),
                ("pdf_content", models.BinaryField()),
                ("source_text", models.TextField(blank=True, editable=False)),
                (
                    "warnings",
                    models.JSONField(
                        default=list, editable=False, verbose_name="Avisos de processamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Processado"),
                            ("needs_review", "Requer conferência"),
                        ],
                        default="processed",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_menu_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="MenuMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Data")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("snack", "Colação"),
                            ("nursery_snack", "Colação do berçário"),
                            ("lunch", "Almoço"),
                            ("departure_meal", "Refeição de saída"),
                            ("dessert", "Sobremesa"),
                        ],
                        max_length=24,
                        verbose_name="Refeição",
                    ),
                ),
                ("description", models.TextField(verbose_name="Preparação")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meals",
                        to="core.menudocument",
                    ),
                ),
            ],
            options={
                "ordering": ["service_date", "meal_type", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "service_date", "meal_type"),
                        name="unique_menu_meal_per_day",
                    )
                ],
            },
        ),
    ]
