# Generated by Django 5.2.17 on 2026-09-29 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_menudocument_menumeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Data do descarte"
                    ),
                ),
                ("observation", models.TextField(max_length=1000, verbose_name="Observação")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_records",
                        to="core.unit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="DisposalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_name", models.CharField(max_length=180, verbose_name="Nome do arquivo")),
                ("content_type", models.CharField(max_length=30)),
                ("image_content", models.BinaryField()),
                ("image_sha256", models.CharField(editable=False, max_length=64)),
                ("width", models.PositiveIntegerField(editable=False)),
                ("height", models.PositiveIntegerField(editable=False)),
                ("size", models.PositiveIntegerField(editable=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="core.disposalrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="disposalrecord",
            index=models.Index(
                fields=["unit", "occurred_on"], name="core_dispos_unit_id_6455a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="disposalphoto",
            constraint=models.UniqueConstraint(
                fields=("record", "image_sha256"), name="unique_disposal_photo_per_record"
            ),
        ),
    ]
