# Generated by Django 5.2.17 on 2026-09-29 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_disposalrecord_disposalphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Data")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("snack", "Colação"),
                            ("nursery_snack", "Colação do berçário"),
                            ("lunch", "Almoço"),
                            ("departure_meal", "Refeição de saída"),
                            ("dessert", "Sobremesa"),
                        ],
                        max_length=24,
                        verbose_name="Refeição",
                    ),
                ),
                ("description", models.TextField(verbose_name="Preparação")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_menu_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_menu_items",
                        to="core.menumeal",
                        verbose_name="Opção de prato",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_menu_items_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["service_date", "meal_type", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_date", "meal_type"),
                        name="unique_weekly_menu_item_per_meal",
                    )
                ],
            },
        ),
    ]
