from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="home"),
    path("entrar/", views.SignInView.as_view(), name="login"),
    path("criar-conta/", views.register, name="register"),
    path("criar-conta/enviado/", views.registration_submitted, name="registration_submitted"),
    path("sair/", views.SignOutView.as_view(), name="logout"),
    path("senha/", views.password_change, name="password_change"),
    path("health/", views.health, name="health"),
    path("painel/", views.dashboard, name="dashboard"),
    path(
        "visualizar-como-funcionario/",
        views.employee_preview,
        name="employee_preview",
    ),
    path(
        "visualizar-como-funcionario/sair/",
        views.employee_preview_exit,
        name="employee_preview_exit",
    ),
    path("unidades/", views.units, name="units"),
    path("estoque/atencao/", views.stock_alerts, name="stock_alerts"),
    path("unidades/nova/", views.unit_edit, name="unit_create"),
    path("unidades/<int:pk>/", views.unit_detail, name="unit_detail"),
    path("unidades/<int:pk>/editar/", views.unit_edit, name="unit_edit"),
    path(
        "unidades/<int:unit_pk>/alimentos/<int:pk>/quantidade/",
        views.adjust_unit_food_quantity,
        name="unit_food_quantity",
    ),
    path("unidades/<int:unit_pk>/alimentos/novo/", views.unit_food_edit, name="unit_food_create"),
    path("unidades/<int:unit_pk>/alimentos/<int:pk>/", views.unit_food_edit, name="unit_food_edit"),
    path("alimentos/", views.foods, name="foods"),
    path("alimentos/novo/", views.food_edit, name="food_create"),
    path("alimentos/<int:pk>/", views.food_detail, name="food_detail"),
    path("alimentos/<int:pk>/editar/", views.food_edit, name="food_edit"),
    path("catalogo-pnae/", views.pnae_catalog, name="pnae_catalog"),
    path("atualizacoes/", views.product_updates, name="product_updates"),
    path("cardapios/", views.menu_documents, name="menu_documents"),
    path("cardapios/enviar/", views.menu_document_upload, name="menu_document_upload"),
    path(
        "cardapios/planejamento/salvar/",
        views.weekly_menu_item_save,
        name="weekly_menu_item_save",
    ),
    path(
        "cardapios/planejamento/<int:pk>/remover/",
        views.weekly_menu_item_delete,
        name="weekly_menu_item_delete",
    ),
    path("cardapios/<int:pk>/", views.menu_document_detail, name="menu_document_detail"),
    path(
        "cardapios/<int:pk>/pdf/",
        views.menu_document_download,
        name="menu_document_download",
    ),
    path("descartes/", views.disposal_records, name="disposal_records"),
    path("descartes/novo/", views.disposal_record_create, name="disposal_record_create"),
    path("descartes/<int:pk>/", views.disposal_record_detail, name="disposal_record_detail"),
    path(
        "descartes/<int:pk>/fotos/<int:photo_pk>/",
        views.disposal_photo,
        name="disposal_photo",
    ),
    path("movimentacoes/", views.stock_movements, name="stock_movements"),
    path("movimentacoes/nova/", views.stock_movement_create, name="stock_movement_create"),
    path(
        "movimentacoes/<int:pk>/",
        views.stock_movement_detail,
        name="stock_movement_detail",
    ),
    path(
        "movimentacoes/<int:pk>/estornar/",
        views.stock_movement_reverse,
        name="stock_movement_reverse",
    ),
    path("notas-fiscais/", views.fiscal_documents, name="fiscal_documents"),
    path(
        "notas-fiscais/importar/",
        views.fiscal_document_upload,
        name="fiscal_document_upload",
    ),
    path(
        "notas-fiscais/receber-pdf/",
        views.fiscal_pdf_upload,
        name="fiscal_pdf_upload",
    ),
    path(
        "notas-fiscais/pdf/<int:pk>/",
        views.fiscal_pdf_download,
        name="fiscal_pdf_download",
    ),
    path(
        "notas-fiscais/<int:pk>/",
        views.fiscal_document_detail,
        name="fiscal_document_detail",
    ),
    path(
        "notas-fiscais/<int:pk>/xml/",
        views.fiscal_document_download,
        name="fiscal_document_download",
    ),
    path(
        "alimentos/<int:food_pk>/embalagens/nova/",
        views.presentation_edit,
        name="presentation_create",
    ),
    path(
        "alimentos/<int:food_pk>/embalagens/<int:pk>/",
        views.presentation_edit,
        name="presentation_edit",
    ),
    path("categorias/", views.categories, name="categories"),
    path("categorias/nova/", views.category_edit, name="category_create"),
    path("categorias/<int:pk>/", views.category_edit, name="category_edit"),
    path("usuarios/", views.users, name="users"),
    path("usuarios/novo/", views.user_edit, name="user_create"),
    path("usuarios/<int:pk>/", views.user_detail, name="user_detail"),
    path("usuarios/<int:pk>/editar/", views.user_edit, name="user_edit"),
    path("usuarios/<int:pk>/aprovar/", views.approve_user, name="approve_user"),
    path("usuarios/<int:pk>/recusar/", views.reject_user, name="reject_user"),
    path("usuarios/<int:pk>/senha/", views.reset_password, name="reset_password"),
    path("usuarios/<int:user_pk>/acessos/novo/", views.access_edit, name="access_create"),
    path("usuarios/<int:user_pk>/acessos/<int:pk>/", views.access_edit, name="access_edit"),
    path("auditoria/", views.audit_list, name="audit"),
    path("auditoria/<int:pk>/", views.audit_detail, name="audit_detail"),
]
